server:
  port: 8081
spring:
  datasource:
    password: 123456
    username: exam
    url: jdbc:mysql://114.67.67.180/exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000
  #文件上传
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 4MB
      max-request-size: 200MB
  #邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 2962598997@qq.com
    password: lgfnhwepndoldchb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  #静态资源
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

mybatis:
  type-aliases-package: cn.ctlyt.exam.pojo

#pagehelper配置项
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

#打印Mybatis生成的SQL
logging:
  level:
    cn.ctlyt.exam.mapper: debug